name: C/C++ CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install libs
      run: sudo apt-get install check
    - name: make
      run: make
    - name: make test
      run: make test
